apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates
        - name: exporter
          image: nginx/nginx-prometheus-exporter:0.10
          ports:
            - name: http-metrics
              containerPort: 9113
          args:
            - -nginx.scrape-uri=http://127.0.0.1:8080/stub_status
      volumes:
        - name: nginx-templates
          configMap:
            name: app-example-nginx-templates
