apiVersion: v1
kind: Service
metadata:
  name: grpc-hostname-server
spec:
  clusterIP: None
  selector:
    app: grpc-hostname-server
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
