apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
